---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: inputs.context.fn.kubecore.io
spec:
  group: context.fn.kubecore.io
  names:
    categories:
    - crossplane
    - function
    kind: Input
    listKind: InputList
    plural: inputs
    singular: input
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: Input for KubeCore Platform Context Function.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: InputSpec defines the input parameters for context resolution.
            properties:
              query:
                type: object
                description: "Query configuration for context resolution"
                properties:
                  resourceType:
                    type: string
                    description: "Type of resource requesting context (e.g., XApp, XKubeSystem, XKubEnv)"
                  requestedSchemas:
                    type: array
                    description: "Specific schemas requested (optional - defaults to all accessible)"
                    items:
                      type: string
                  includeFullSchemas:
                    type: boolean
                    description: "Whether to include full schemas or just metadata"
                    default: true
                required:
                  - resourceType
            required:
              - query
            type: object
        required: []
        type: object
    served: true
    storage: true
